# Generated by Django 2.2 on 2019-08-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(blank=True, max_length=128, verbose_name='password'),
        ),
    ]
